version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11

    steps:
      - checkout
      - run: python main.py

  test:
    docker:
      - image: cimg/python:3.11
    
    steps:
      - checkout
      - run: python tests.py
  
  deploy:
    docker:
      - image: cimg\python:3.11
    
    steps:
      - run: echo "Practical Complete"

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test